### ISSUE TITLE
Builds for 64-bit Windows have become available as of PyPy v7.3.4

### ISSUE THREAD

**Issue by QuaternionsRock** [conda-forge/pypy3.6-feedstock#39]
There is no longer any reason for the  pypy3.7 package in conda-forge not to support Windows. I do not currently have the time to learn how conda packages are built, or else I would create the PR myself.

**Comment by h-vetinari** [comment]
The main part will be rewriting https://github.com/conda-forge/pypy3.6-feedstock/blob/master/recipe/build.sh to a windows `bld.bat` file.

If you want, I can open a PR with the basic setup, and give you push access to my fork of this feedstock. I'd be happy to help as well, but don't have time to look into it in depth right now.

**Comment by h-vetinari** [comment]
(alternatively, it doesn't have to be a translation of the existing `build.sh` here, one could equally start from the upstream build scripts for windows)

**Comment by mattip** [comment]
Unfortunately it is  a bit complicated to translate (compile) 64-bit windows PyPy. In order to build from source, you must use either [this cpython6464 fork of CPython](https://github.com/nulano/cpython) or download a PyPy2.7 for windows 64 and use that as the host python for translation. Another path would be to download the compiled PyPy3.7, apply patches to the pure-python `lib-python/3.7` and `lib_pypy`, and repackage for conda. 

Is there precedent for downloading a binary blob as part of the build process?

**Comment by isuruf** [comment]
> In order to build from source, you must use either this cpython6464 fork of CPython or download a PyPy2.7 for windows 64 and use that as the host python for translation.

Either of these is fine. In https://github.com/conda-forge/openjdk-feedstock/blob/master/recipe/meta.yaml, we download a precompiled jdk for linux and use it to compile the jdk from source.

**Comment by h-vetinari** [comment]
Sounds like downloading the PyPy2.7 for windows 64 would be better (at least in terms of CI runtime), as otherwise we'd have to build the cpython6464 fork here as well...?

**Comment by QuaternionsRock** [comment]
> Unfortunately it is a bit complicated to translate (compile) 64-bit windows PyPy. In order to build from source, you must use either [this cpython6464 fork of CPython](https://github.com/nulano/cpython) or download a PyPy2.7 for windows 64 and use that as the host python for translation. Another path would be to download the compiled PyPy3.7, apply patches to the pure-python `lib-python/3.7` and `lib_pypy`, and repackage for conda.
> 
> Is there precedent for downloading a binary blob as part of the build process?

I am not super knowledgeable on the subject, so my apologies if this a stupid question: I personally believe it would be in the best interest of the community to start with PyPy 3, since the only real use case for PyPy 2 at this point is production code execution that doesn't typically employ Anaconda. I see that cpython6464 is a fork of CPython 2; is it also required to build PyPy 3 from source?

**Comment by mattip** [comment]
"PyPy is a python interpreter written in Python" is too non-specific. It should be restated as "PyPy is a python interpreter written in a variant of Python2 called RPython". So the steps in the recipe are:
1. download the source tarball of the the RPython code for the python3.7 interpreter
2. install an environment that includes a python interpreter that can convert this source code into an executable
3. run the interpreter
4. package the result as a conda package

Here we are discussing the best policy for step 2 since that interpreter must be a python2 interpreter. Specifically, for windows64 it needs to be either cpython6464 or pypy2.7-7.3.4

**Comment by mattip** [comment]
> If you want, I can open a PR with the basic setup, and give you push access to my fork of this feedstock

Yes please. 
- Is all that is needed is a functioning `bld.bat`
- Does it get a conda environment properly set up using the "requirements" section of the `recipe/meta.yml`?
- Is there a convenient way to properly run the `bld.bat` locally (when I use `python build-locally.py` I get a "not supported" error for windows)?

**Comment by mattip** [comment]
@h-vetinari, @isuruf any thoughts about a PR with a basic setup for a windows build?

**Comment by isuruf** [comment]
> Is there a convenient way to properly run the bld.bat locally (when I use python build-locally.py I get a "not supported" error for windows)?

You can run `conda debug recipe` to get a conda environment setup and after running the instructions printed at the end, you can run `bld.bat`

**Comment by mattip** [comment]
`conda debug recipe` did not complete successfully, there is a package conflict. `conda smithy rerender -c auto` did not update anything. Here is the complete log:

<details>

```
C:\oss\pypy3.6-feedstock>conda debug recipe
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from C:\oss\pypy3.6-feedstock\recipe\conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from C:\oss\pypy3.6-feedstock\recipe\conda_build_config.yaml
Attempting to finalize metadata for pypy3.7
INFO:conda_build.metadata:Attempting to finalize metadata for pypy3.7
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\core\solve.py", line 818, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\resolve.py", line 1322, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda\resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
pkg-config -> glib[version='>=2.58.3,<3.0a0'] -> python[version='*|>=2.7|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
python[version='>=2.7,<3']
pycparser -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|3.4.*']

Package zlib conflicts for:
python[version='>=2.7,<3'] -> sqlite[version='>=3.30.1,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
pkg-config -> libglib[version='>=2.64.6,<3.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']

Package vs2008_runtime conflicts for:
python[version='>=2.7,<3'] -> vc=9 -> vs2008_runtime[version='>=9.0.30729.1,<10.0a0']
python[version='>=2.7,<3'] -> vs2008_runtime

Package sqlite conflicts for:
pycparser -> python -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.35.4,<4.0a0|>=3.35.1,<4.0a0|>=3.35.5,<4.0a0|>=3.34.0,<4.0a0']
python[version='>=2.7,<3'] -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.1,<4.0a0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\oss\Anaconda3_2020_02\Scripts\conda-debug-script.py", line 10, in <module>
    sys.exit(main())
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\cli\main_debug.py", line 94, in main
    return execute(sys.argv[1:])
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\cli\main_debug.py", line 70, in execute
    activation_string = api.debug(thing_to_debug, verbose=(not _args.activate_string_only), **_args.__dict__)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\api.py", line 451, in debug
    metadata_tuples = render(recipe_or_package_path_or_metadata_tuples, config=config, **kwargs)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\api.py", line 52, in render
    bypass_env_check=bypass_env_check):
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\metadata.py", line 2048, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\metadata.py", line 722, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\render.py", line 527, in finalize_metadata
    exclude_pattern)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\render.py", line 390, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\render.py", line 378, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\environ.py", line 759, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
  File "c:\oss\Anaconda3_2020_02\lib\site-packages\conda_build\exceptions.py", line 78, in __init__
    " {}".format(str(conda_exception)))
RuntimeError: failed to parse packages from exception: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
pkg-config -> glib[version='>=2.58.3,<3.0a0'] -> python[version='*|>=2.7|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
python[version='>=2.7,<3']
pycparser -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|3.4.*']

Package zlib conflicts for:
python[version='>=2.7,<3'] -> sqlite[version='>=3.30.1,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
pkg-config -> libglib[version='>=2.64.6,<3.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']

Package vs2008_runtime conflicts for:
python[version='>=2.7,<3'] -> vc=9 -> vs2008_runtime[version='>=9.0.30729.1,<10.0a0']
python[version='>=2.7,<3'] -> vs2008_runtime

Package sqlite conflicts for:
pycparser -> python -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.35.4,<4.0a0|>=3.35.1,<4.0a0|>=3.35.5,<4.0a0|>=3.34.0,<4.0a0']
python[version='>=2.7,<3'] -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.1,<4.0a0']
```

**Comment by mattip** [comment]
Any hints how to get `conda debug recipe` to work on windows?

**Comment by isuruf** [comment]
See https://github.com/conda-forge/pypy3.6-feedstock/pull/41
